NAME: '2d_wafer4_bs16_ps256_loss0.0_slice1.0_cross1.0_interaction1.0'

MODEL:
    input_nc: 1
    output_nc: 16
    filter_channel: 16
    if_sigmoid: False

TRAIN:
    mode: 'x-y-z-2'
    resume: False
    if_valid: True
    if_seg: True
    cache_path: '../caches/'
    save_path: '../models/'
    pad: 0
    loss_func: 'WeightedMSELoss'   # 'WeightedBCELoss', 'BCELoss'
    affs0_weight: 1
    loss_mode: 'trunc'
    if_verse: False
    only_z: False
    opt_type: 'adam'
    total_iters: 200000
    warmup_iters: 0
    base_lr: 0.0001
    end_lr: 0.0001
    display_freq: 100
    valid_freq: 1000
    save_freq: 1000
    decay_iters: 100000
    weight_decay: ~
    power: 1.5

    batch_size: 16
    num_workers: 4
    if_cuda: True
    interaction: True
    loss_interaction: 1.0
    random_seed: 555  # -1 is none
    loss_weight: 0.0
    loss_2d_slice_weight: 1.0
    loss_cross_weight: 1.0
    loss_3d_weight: 1.0


DATA:
    if_sparse: False
    sparse_id: 0
    dataset_name: 'wafer4'  # 'snemi3d-ac3', 'cremi-A', 'cremi'
    valid_dataset: 'wafer4'  # 'snemi3d-ac3', 'cremi-A', 'cremi'
    train_split: 100
    test_split: 25
    data_folder: '../data'
    patch_size:
        - 256
        - 256
    shift_channels: ~
    padding: 50
    if_dilate: True
    widen_way: True
    if_bg: True
    if_scale_aug: True
    if_filp_aug: True
    if_rotation_aug: True
    if_intensity_aug: True
    if_elastic_aug: True


TEST:
    pad: 0
    model_name: '2021-05-09--14-40-12_seg_general_ac4_data80_c16_norm_wz2_aug3'